---
Name: CommerceStockKeeping
After: 'commerce/*'
---
CatalogueProduct:
  extensions:
    - StockKeepingCatalogueProductExtension
Order:
  extensions:
    - StockKeepingOrderExtension
ShoppingCart:
  extensions:
    - StockKeepingShoppingCartExtension
